version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Terraform y dependencias..."
      - curl -L -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Inicializando Terraform..."
      - terraform init -input=false
  build:
    commands:
      - echo "Planeando y aplicando Terraform..."
      - terraform plan -input=false
      - terraform apply -auto-approve
artifacts:
  files:
    - "**/*"
  discard-paths: yes
