version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Instalando dependencias necesarias"
      - pip install --upgrade awscli
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - terraform --version
      - helm version
      - aws eks --version
  pre_build:
    commands:
      - echo "Iniciando Terraform"
      - terraform init
      - terraform apply -auto-approve
      - export VPC_ID=$(terraform output -raw vpc_id)
      - echo "VPC_ID=${VPC_ID}"
  post_build:
    commands:
      - echo "Ejecución completada. VPC_ID=${VPC_ID}"
  build:
    commands:
      - echo "Configurando kubectl para EKS"
      - aws eks update-kubeconfig --region us-east-1 --name eks-rdg
      - echo "Instalando AWS Load Balancer Controller"
      - helm repo add eks https://aws.github.io/eks-charts
      - helm repo update
      - helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
          --set clusterName=eks-rdg \
          --set awsRegion=us-east-1 \
          --set awsVpcID=$VPC_ID \
          --namespace kube-system          
post_build:
    commands:
      - echo "Desplegando aplicación"
      - kubectl apply -f app-deployment.yaml
      - echo "Despliegue completado"
artifacts:
  files:
    - '**/*'